# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ZofiaHalo\Documents\Mongo\Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Menu(object):
    def setupUi(self, Menu):
        Menu.setObjectName("Menu")
        Menu.resize(604, 270)
        self.push_button_reception = QtWidgets.QPushButton(Menu)
        self.push_button_reception.setGeometry(QtCore.QRect(40, 100, 141, 71))
        self.push_button_reception.setObjectName("push_button_reception")
        self.push_button_medician = QtWidgets.QPushButton(Menu)
        self.push_button_medician.setGeometry(QtCore.QRect(230, 100, 141, 71))
        self.push_button_medician.setObjectName("push_button_medician")
        self.push_button_patient = QtWidgets.QPushButton(Menu)
        self.push_button_patient.setGeometry(QtCore.QRect(420, 100, 141, 71))
        self.push_button_patient.setObjectName("push_button_patient")
        self.label_menu = QtWidgets.QLabel(Menu)
        self.label_menu.setGeometry(QtCore.QRect(180, 30, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_menu.setFont(font)
        self.label_menu.setObjectName("label_menu")

        self.retranslateUi(Menu)
        QtCore.QMetaObject.connectSlotsByName(Menu)

    def retranslateUi(self, Menu):
        _translate = QtCore.QCoreApplication.translate
        Menu.setWindowTitle(_translate("Menu", "Form"))
        self.push_button_reception.setText(_translate("Menu", "Reception"))
        self.push_button_medician.setText(_translate("Menu", "Medician"))
        self.push_button_patient.setText(_translate("Menu", "Patient"))
        self.label_menu.setText(_translate("Menu", "Choose your access level"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Menu = QtWidgets.QWidget()
    ui = Ui_Menu()
    ui.setupUi(Menu)
    Menu.show()
    sys.exit(app.exec_())
