# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ZofiaHalo\Documents\Mongo\ScheduleAppointment.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScheduleAppointment(object):
    def setupUi(self, ScheduleAppointment):
        ScheduleAppointment.setObjectName("ScheduleAppointment")
        ScheduleAppointment.resize(323, 294)
        self.push_button_schedule = QtWidgets.QPushButton(ScheduleAppointment)
        self.push_button_schedule.setGeometry(QtCore.QRect(110, 240, 121, 31))
        self.push_button_schedule.setObjectName("push_button_schedule")
        self.label_pesel = QtWidgets.QLabel(ScheduleAppointment)
        self.label_pesel.setGeometry(QtCore.QRect(40, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_pesel.setFont(font)
        self.label_pesel.setObjectName("label_pesel")
        self.label_time = QtWidgets.QLabel(ScheduleAppointment)
        self.label_time.setGeometry(QtCore.QRect(40, 90, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        self.label_specialization = QtWidgets.QLabel(ScheduleAppointment)
        self.label_specialization.setGeometry(QtCore.QRect(40, 140, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_specialization.setFont(font)
        self.label_specialization.setObjectName("label_specialization")
        self.line_edit_pesel = QtWidgets.QLineEdit(ScheduleAppointment)
        self.line_edit_pesel.setGeometry(QtCore.QRect(170, 50, 121, 20))
        self.line_edit_pesel.setObjectName("line_edit_pesel")
        self.combo_box_specialization = QtWidgets.QComboBox(ScheduleAppointment)
        self.combo_box_specialization.setGeometry(QtCore.QRect(170, 140, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_box_specialization.setFont(font)
        self.combo_box_specialization.setObjectName("combo_box_specialization")
        self.combo_box_specialization.addItem("")
        self.label_header = QtWidgets.QLabel(ScheduleAppointment)
        self.label_header.setGeometry(QtCore.QRect(70, 10, 201, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.date_time_edit = QtWidgets.QDateTimeEdit(ScheduleAppointment)
        self.date_time_edit.setGeometry(QtCore.QRect(170, 90, 121, 31))
        self.date_time_edit.setObjectName("date_time_edit")
        self.label_physicans_name = QtWidgets.QLabel(ScheduleAppointment)
        self.label_physicans_name.setGeometry(QtCore.QRect(40, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_physicans_name.setFont(font)
        self.label_physicans_name.setObjectName("label_physicans_name")
        self.combo_box_physicans_name = QtWidgets.QComboBox(ScheduleAppointment)
        self.combo_box_physicans_name.setGeometry(QtCore.QRect(170, 180, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_box_physicans_name.setFont(font)
        self.combo_box_physicans_name.setObjectName("combo_box_physicans_name")
        self.combo_box_physicans_name.addItem("")

        self.retranslateUi(ScheduleAppointment)
        QtCore.QMetaObject.connectSlotsByName(ScheduleAppointment)

    def retranslateUi(self, ScheduleAppointment):
        _translate = QtCore.QCoreApplication.translate
        ScheduleAppointment.setWindowTitle(_translate("ScheduleAppointment", "Form"))
        self.push_button_schedule.setText(_translate("ScheduleAppointment", "Schedule"))
        self.label_pesel.setText(_translate("ScheduleAppointment", "Patient PESEL"))
        self.label_time.setText(_translate("ScheduleAppointment", "Time of appointment"))
        self.label_specialization.setText(_translate("ScheduleAppointment", "Physican\'s specialization"))
        self.combo_box_specialization.setItemText(0, _translate("ScheduleAppointment", "XYZ"))
        self.label_header.setText(_translate("ScheduleAppointment", "Schedule appointment"))
        self.label_physicans_name.setText(_translate("ScheduleAppointment", "Physican\'s name"))
        self.combo_box_physicans_name.setItemText(0, _translate("ScheduleAppointment", "XYZ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScheduleAppointment = QtWidgets.QWidget()
    ui = Ui_ScheduleAppointment()
    ui.setupUi(ScheduleAppointment)
    ScheduleAppointment.show()
    sys.exit(app.exec_())
