# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ZofiaHalo\Documents\Mongo\LinkPhysician.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LinkPhysician(object):
    def setupUi(self, LinkPhysician):
        LinkPhysician.setObjectName("LinkPhysician")
        LinkPhysician.resize(323, 227)
        self.push_button_link = QtWidgets.QPushButton(LinkPhysician)
        self.push_button_link.setGeometry(QtCore.QRect(100, 160, 121, 31))
        self.push_button_link.setObjectName("push_button_link")
        self.label_no_pwz = QtWidgets.QLabel(LinkPhysician)
        self.label_no_pwz.setGeometry(QtCore.QRect(40, 50, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_no_pwz.setFont(font)
        self.label_no_pwz.setObjectName("label_no_pwz")
        self.label_header = QtWidgets.QLabel(LinkPhysician)
        self.label_header.setGeometry(QtCore.QRect(40, 10, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.combo_box_no_pwz = QtWidgets.QComboBox(LinkPhysician)
        self.combo_box_no_pwz.setGeometry(QtCore.QRect(170, 50, 121, 22))
        self.combo_box_no_pwz.setObjectName("combo_box_no_pwz")
        self.label_specialization = QtWidgets.QLabel(LinkPhysician)
        self.label_specialization.setGeometry(QtCore.QRect(40, 100, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_specialization.setFont(font)
        self.label_specialization.setObjectName("label_specialization")
        self.combo_box_specialization = QtWidgets.QComboBox(LinkPhysician)
        self.combo_box_specialization.setGeometry(QtCore.QRect(170, 100, 121, 22))
        self.combo_box_specialization.setObjectName("combo_box_specialization")

        self.retranslateUi(LinkPhysician)
        QtCore.QMetaObject.connectSlotsByName(LinkPhysician)

    def retranslateUi(self, LinkPhysician):
        _translate = QtCore.QCoreApplication.translate
        LinkPhysician.setWindowTitle(_translate("LinkPhysician", "Form"))
        self.push_button_link.setText(_translate("LinkPhysician", "Link"))
        self.label_no_pwz.setText(_translate("LinkPhysician", "No PWZ"))
        self.label_header.setText(_translate("LinkPhysician", "Link physician to specialization"))
        self.label_specialization.setText(_translate("LinkPhysician", "Specialization"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LinkPhysician = QtWidgets.QWidget()
    ui = Ui_LinkPhysician()
    ui.setupUi(LinkPhysician)
    LinkPhysician.show()
    sys.exit(app.exec_())
