# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ZofiaHalo\Documents\Mongo\gui\Medician2.2.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Medician2(object):
    def setupUi(self, self):
        self.setObjectName("Medician2")
        self.resize(815, 643)
        self.apply_pwz_push_button = QtWidgets.QPushButton(self)
        self.apply_pwz_push_button.setGeometry(QtCore.QRect(610, 50, 161, 32))
        self.apply_pwz_push_button.setObjectName("apply_pwz_push_button")
        self.pwz_line_edit = QtWidgets.QLineEdit(self)
        self.pwz_line_edit.setGeometry(QtCore.QRect(610, 20, 161, 21))
        self.pwz_line_edit.setText("")
        self.pwz_line_edit.setObjectName("pwz_line_edit")
        self.display_text_edit = QtWidgets.QTextEdit(self)
        self.display_text_edit.setGeometry(QtCore.QRect(20, 40, 521, 181))
        self.display_text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.display_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.display_text_edit.setReadOnly(True)
        self.display_text_edit.setObjectName("display_text_edit")
        self.label_visits = QtWidgets.QLabel(self)
        self.label_visits.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_visits.setObjectName("label_visits")
        self.push_button_ref = QtWidgets.QPushButton(self)
        self.push_button_ref.setGeometry(QtCore.QRect(690, 460, 111, 24))
        self.push_button_ref.setObjectName("push_button_ref")
        self.push_button_presc = QtWidgets.QPushButton(self)
        self.push_button_presc.setGeometry(QtCore.QRect(560, 500, 111, 24))
        self.push_button_presc.setObjectName("push_button_presc")
        self.push_button_desc = QtWidgets.QPushButton(self)
        self.push_button_desc.setGeometry(QtCore.QRect(560, 460, 111, 24))
        self.push_button_desc.setObjectName("push_button_desc")
        self.return_push_button = QtWidgets.QPushButton(self)
        self.return_push_button.setGeometry(QtCore.QRect(560, 590, 241, 31))
        self.return_push_button.setObjectName("return_push_button")
        self.display_history_text_edit = QtWidgets.QTextEdit(self)
        self.display_history_text_edit.setGeometry(QtCore.QRect(20, 280, 521, 341))
        self.display_history_text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.display_history_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.display_history_text_edit.setReadOnly(True)
        self.display_history_text_edit.setObjectName("display_history_text_edit")
        self.label_history = QtWidgets.QLabel(self)
        self.label_history.setGeometry(QtCore.QRect(20, 260, 101, 16))
        self.label_history.setObjectName("label_history")
        self.label_appointment = QtWidgets.QLabel(self)
        self.label_appointment.setGeometry(QtCore.QRect(640, 300, 81, 20))
        self.label_appointment.setObjectName("label_appointment")
        self.combo_box_appointments = QtWidgets.QComboBox(self)
        self.combo_box_appointments.setGeometry(QtCore.QRect(560, 330, 241, 26))
        self.combo_box_appointments.setObjectName("combo_box_appointments")
        self.label_patient_2 = QtWidgets.QLabel(self)
        self.label_patient_2.setGeometry(QtCore.QRect(650, 110, 131, 16))
        self.label_patient_2.setObjectName("label_patient_2")
        self.combo_box_date = QtWidgets.QComboBox(self)
        self.combo_box_date.setGeometry(QtCore.QRect(560, 140, 241, 26))
        self.combo_box_date.setObjectName("combo_box_date")
        self.apply_date_push_button = QtWidgets.QPushButton(self)
        self.apply_date_push_button.setGeometry(QtCore.QRect(610, 180, 161, 32))
        self.apply_date_push_button.setObjectName("apply_date_push_button")
        self.apply_appointment_push_button = QtWidgets.QPushButton(self)
        self.apply_appointment_push_button.setGeometry(QtCore.QRect(600, 370, 161, 32))
        self.apply_appointment_push_button.setObjectName("apply_appointment_push_button")

        QtCore.QMetaObject.connectSlotsByName(self)
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Medician2", "Form"))
        self.apply_pwz_push_button.setText(_translate("Medician2", "Apply"))
        self.pwz_line_edit.setPlaceholderText(_translate("Medician2", "Insert your PWZ"))
        self.label_visits.setText(_translate("Medician2", "Visits"))
        self.push_button_ref.setText(_translate("Medician2", "Add referral"))
        self.push_button_presc.setText(_translate("Medician2", "Add prescription"))
        self.push_button_desc.setText(_translate("Medician2", "Add description"))
        self.return_push_button.setText(_translate("Medician2", "Return"))
        self.label_history.setText(_translate("Medician2", "Medical history"))
        self.label_appointment.setText(_translate("Medician2", "Appointment"))
        self.label_patient_2.setText(_translate("Medician2", "Select date"))
        self.apply_date_push_button.setText(_translate("Medician2", "Apply"))
        self.apply_appointment_push_button.setText(_translate("Medician2", "Apply"))

