from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_Show_appointments(QMainWindow):
    def __init__(self, mongo_manager):
        super().__init__()
        self.setObjectName("Show_appointments")
        self.resize(752, 611)
        self.label_header = QtWidgets.QLabel(self)
        self.label_header.setGeometry(QtCore.QRect(320, 0, 171, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_header.setFont(font)
        self.label_header.setObjectName("label_header")
        self.push_button_display = QtWidgets.QPushButton(self)
        self.push_button_display.setGeometry(QtCore.QRect(580, 80, 71, 21))
        self.push_button_display.setObjectName("push_button_display")
        self.return_push_button = QtWidgets.QPushButton(self)
        self.return_push_button.setGeometry(QtCore.QRect(660, 80, 71, 21))
        self.return_push_button.setObjectName("return_push_button")
        self.display_text_edit = QtWidgets.QTextEdit(self)
        self.display_text_edit.setGeometry(QtCore.QRect(30, 150, 691, 431))
        self.display_text_edit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.display_text_edit.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.display_text_edit.setReadOnly(True)
        self.display_text_edit.setObjectName("display_text_edit")
        self.line_edit_pesel = QtWidgets.QLineEdit(self)
        self.line_edit_pesel.setGeometry(QtCore.QRect(40, 80, 121, 20))
        self.line_edit_pesel.setObjectName("line_edit_pesel")
        self.date_edit = QtWidgets.QDateEdit(self)
        self.date_edit.setGeometry(QtCore.QRect(180, 80, 110, 21))
        self.date_edit.setObjectName("date_edit")
        self.combo_box_physicans_name = QtWidgets.QComboBox(self)
        self.combo_box_physicans_name.setGeometry(QtCore.QRect(300, 80, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_box_physicans_name.setFont(font)
        self.combo_box_physicans_name.setObjectName("combo_box_physicans_name")
        self.combo_box_physicans_name.addItem("")
        self.label_date = QtWidgets.QLabel(self)
        self.label_date.setGeometry(QtCore.QRect(180, 50, 55, 16))
        self.label_date.setObjectName("label_date")
        self.label_physicians_name = QtWidgets.QLabel(self)
        self.label_physicians_name.setGeometry(QtCore.QRect(300, 50, 121, 16))
        self.label_physicians_name.setObjectName("label_physicians_name")
        self.label_filter = QtWidgets.QLabel(self)
        self.label_filter.setGeometry(QtCore.QRect(40, 50, 55, 16))
        self.label_filter.setObjectName("label_filter")
        self.combo_box_specialization = QtWidgets.QComboBox(self)
        self.combo_box_specialization.setGeometry(QtCore.QRect(430, 80, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.combo_box_specialization.setFont(font)
        self.combo_box_specialization.setObjectName("combo_box_specialization")
        self.combo_box_specialization.addItem("")
        self.label_physicians_specialization = QtWidgets.QLabel(self)
        self.label_physicians_specialization.setGeometry(QtCore.QRect(430, 50, 151, 16))
        self.label_physicians_specialization.setObjectName("label_physicians_specialization")
        QtCore.QMetaObject.connectSlotsByName(self)

        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Show_appointments", "Form"))
        self.label_header.setText(_translate("Show_appointments", "Appointments"))
        self.push_button_display.setText(_translate("Show_appointments", "Display"))
        self.return_push_button.setText(_translate("Show_appointments", "Return"))
        self.line_edit_pesel.setPlaceholderText(_translate("Show_appointments", "Patient PESEL"))
        self.combo_box_physicans_name.setItemText(0, _translate("Show_appointments", "XYZ"))
        self.label_date.setText(_translate("Show_appointments", "Date"))
        self.label_physicians_name.setText(_translate("Show_appointments", "Physician\'s name"))
        self.label_filter.setText(_translate("Show_appointments", "Filter:"))
        self.combo_box_specialization.setItemText(0, _translate("Show_appointments", "XYZ"))
        self.label_physicians_specialization.setText(_translate("Show_appointments", "Physician\'s specialization"))
        
        self.mongo_manager = mongo_manager
        self.return_push_button.clicked.connect(self.return_push_button_clicked)
        self.push_button_display.clicked.connect(self.push_button_display_clicked)

    def return_push_button_clicked(self):
        self.close()

    def push_button_display_clicked(self):
        print("hjgjhg")


